other_parameters:
    description: "A different styled parameters file to go into the train2 (Spinning-up style) algorithm"
training_parameters:
    train2: True
    networks:
        policy:
            lr: 0.003
            hidden_layers:
                l1: 512
                l2: 512
        q:
            lr: 0.003
            hidden_layers:
                l1: 512
                l2: 512
    algorithm:    
        num_iterations: 400000
        human: False
        len_episode: 200
        batch_size: 512
        gamma: 0.99
        alpha: 0.2
        gradient_after: 1000
        gradient_every: 50
        save_every: 10000
    reward_function:
        cost: True
        cost_scale: 0.0142857
        raise: 1
        
    configuration_save_name: "train2_big"
    rb_save_name: "train2_big"
