# config.yaml
env:
  name: "Lift"
  robots: "Kinova"
  reward_shaping: true
  reward_scale: 1.0
  use_camera_obs: false
  has_renderer: false
  has_offscreen_renderer: false
  control_freq: 20

training:
  total_timesteps: 500000
  learning_rate: 0.001
  buffer_size: 100000
  batch_size: 256
  gamma: 0.99
  tau: 0.005
  action_noise_sigma: 0.1

logging:
  tensorboard_log: "./tensorboard/"
  monitor_log: "./logdir/"

model:
  save_path: "ddpg_kinova_lift_model"
