other_parameters:
    description: "A different styled parameters file to go into the train2 (Spinning-up style) algorithm with HER"
training_parameters:
    train2: True
    HER: True
    bonus: 1
    networks:
        policy:
            lr: 0.003
            hidden_layers:
                l1: 256
                l2: 256
        q:
            lr: 0.003
            hidden_layers:
                l1: 256
                l2: 256
    algorithm:    
        num_iterations: 200000
        human: False
        len_episode: 200
        batch_size: 256
        gamma: 0.99
        alpha: 0.2
        gradient_after: 1000
        gradient_every: 50
        save_every: 10000
    reward_function:
        cost: False
        raise: 1
        
    configuration_save_name: "6"
    rb_save_name: "6_teleop"
