other_parameters:
    description: "This is the default parameters file."
training_parameters:  
    networks:
        policy:
            lr: 0.0003
            hidden_layers:
                l1: 256
                l2: 256
        q:
            lr: 0.0003
            hidden_layers:
                l1: 256
                l2: 256
    algorithm:    
        num_iterations: 1000000
        human: False
        len_episode: 100
        num_action_episodes: 50
        batch_size: 64
        gamma: 0.99
        alpha: 0.2
        num_gradient_steps: 1000
    reward_function:
        cost: True
        cost_scale: 0.142857
        raise: 1
        
    configuration_name: "standard"
    rb_save_name: "raised_cost_w_backwards"
