other_parameters:
    
training_parameters:
    policy_lr: 0.0003
    q1_lr: 0.0003
    q2_lr: 0.0003
    num_iterations: 1
    human: True
    len_episode: 50
    num_action_episodes: 10
    rb_save_name: "hum_raised_cost"
    batch_size: 64
    gamma: 0.99
    alpha: 0.2
    num_gradient_steps: 0
    policy_save_name: "dump_pi"
    critic1_save_name: "dump_q"
    critic2_save_name: "dump_q"
    

