other_parameters:
    
training_parameters:
    policy_lr: 0.0003
    q_lr: 0.0003
    num_iterations: 1
    len_episode: 50
    num_action_episodes: 10
    human: False
    rb_save_name: "mixed_v1"
    batch_size: 64
    gamma: 0.99
    alpha: 0.2
    num_gradient_steps: 1000
    policy_save_name: "mixed_pi_v1"
    qnetwork_save_name: "mixed_q_v1"
    

