other_parameters:
    description: "This is the practice parameters file."
training_parameters:
    replay_buffer: "teleop_raised"
    networks:
        policy:
            lr: 0.0003
            hidden_layers:
                l1: 256
                l2: 256
        q:
            lr: 0.0003
            hidden_layers:
                l1: 256
                l2: 256
    algorithm:    
        num_iterations: 50
        human: False
        len_episode: 100
        num_action_episodes: 5
        batch_size: 256
        gamma: 0.99
        alpha: 0.2
        num_gradient_steps: 5000
    reward_function:
        cost: True
        cost_scale: 0.142857
        raise: 1
        
    configuration_save_name: "practice"
    rb_save_name: "raised_w_backwards"
