other_parameters:
    description: "An example objective in the new RL set up."
objective:
    components:
        move_eef:
            composition: "reset_eef"
            component:
                A-tuning:
                    lr: 0.003
                HER: False
                teleop: False
                bonus: False
                networks:
                    lr: 0.003
                    hidden_layers:
                        l1: 256
                        l2: 256
                    state_dim: 9
                    action_dim: 3
                pi:
                    inputs: [
                        "eef_pos",
                        "cube_pos",
                        "eef_cube_displacement"
                        ]
                    outputs:
                        ["eef_desired_move"]
                reward:
                    eef_cube_distance: 1.0
                algorithm:
                    num_iterations: 500
                    len_episode: 50
                    gamma: 0.99
                    gradient_after: 100
                    batch_size: 16
                    gradient_every: 50
                    save_every: 50000
                    networks_save_name: "eef->cube"
                    rb_save_name: "dump"
        carry_cube:
            composition: "reset_eef"
            component:
                A-tuning:
                    lr: 0.003
                HER: False
                teleop: False
                bonus: False
                networks:
                    lr: 0.003
                    hidden_layers:
                        l1: 256
                        l2: 256
                    state_dim: 9
                    action_dim: 3
                pi:
                    inputs: [
                        "cube_pos",
                        "cube_goal_pos",
                        "cube_cube_displacement"
                        ]
                    outputs:
                        ["eef_desired_move"]
                reward:
                    cube_cube_distance: 1.0
                algorithm:
                    num_iterations: 500
                    len_episode: 50
                    gamma: 0.99
                    gradient_after: 100
                    batch_size: 16
                    gradient_every: 50
                    save_every: 50000
                    networks_save_name: "cube->cube"
                    rb_save_name: "dump"
    reset_eef:
        compositor: "reset_eef" 
    
    midway_eef:
        compositor: "midway_eef"
    

    


    
