other_parameters:
    description: "Parameters for starting a replay buffer with 3 teleop episodes."
training_parameters:
    networks:
        policy:
            lr: 0.003
            hidden_layers:
                l1: 256
                l2: 256
        q:
            lr: 0.003
            hidden_layers:
                l1: 256
                l2: 256
    algorithm:    
        num_iterations: 3
        human: True
        num_action_episodes: 0
        len_episode: 100
        num_gradient_steps: 0
        batch_size: 0
        gamma: 0
        alpha: 0
    reward_function:
        cost: False
        raise: 1
        
    configuration_save_name: "dump"
    rb_save_name: "teleop_raised"
