other_parameters:
    description: "This a parameters file that TESTS the practice configuration."
training_parameters:
    configuration: "practice"
    testing: True
    networks:
        policy:
            lr: 0.0003
            hidden_layers:
                l1: 256
                l2: 256
        q:
            lr: 0.0003
            hidden_layers:
                l1: 256
                l2: 256
    algorithm:    
        num_iterations: 0
        human: False
        len_episode: 0
        num_action_episodes: 0
        batch_size: 0
        gamma: 0
        alpha: 0
        num_gradient_steps: 0
    reward_function:
        cost: True
        cost_scale: 0.142857
        raise: 1
        
    configuration_save_name: "practice"
    rb_save_name: "raised_cost_w_backwards"
