other_parameters:
    
training_parameters:
    policy_lr: 0.0003
    q_lr: 0.0003
    num_iterations: 0
    len_episode: 50
    num_action_episodes: 0
    rb_save_name: "none"
    batch_size: 64
    gamma: 0.99
    alpha: 0.2
    num_gradient_steps: 0
    policy_save_name: "mixed_pi_v1"
    qnetwork_save_name: "mixed_q_v1"
    

