other_parameters:
    
training_parameters:
    policy_lr: 0.0003
    q_lr: 0.0003
    num_iterations: 100
    len_episode: 50
    num_action_episodes: 100
    saved_rb_name: "1raise_1e-1else_v1"
    batch_size: 64
    gamma: 0.99
    alpha: 0.2
    num_gradient_steps: 10
    saved_model_name: "trained_policy"
    

